### ISSUE TITLE
BSOD code excluded

### ISSUE THREAD

**Issue by Jacoblightning** [theunrealtarik/malformed#1]
Correct me if i'm wrong, but I looked over the code and it looks like you started working on the bsod part at [this](https://github.com/theunrealtarik/malformed/commit/4cb313bd54521a8243938584c3fe31c7b99da6a5) commit but you also added the code for it to gitignore, could you please add the code to the main repo?

**Comment by theunrealtarik** [comment]
Well, I did ignore it for an obvious reason that is the fear of mis use.

**Comment by theunrealtarik** [comment]
Code has been included with [this](https://github.com/theunrealtarik/malformed/commit/ba5e5ff4ec1eadce05eb2e9a21967b76633a4553) commit. I hope it helps.
